# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_ROOT = "../../../vagrant"

Vagrant.configure("2") do |config|
  config.vm.box = "Ubuntu32-12.04LTS"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.hostname = "jvm"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :private_network, ip: "192.168.33.10", auto_correct: true
  # config.vm.network :public_network
  # config.ssh.forward_agent = false
  config.vm.synced_folder VAGRANT_ROOT, "/vagrant"

  config.vm.provision :shell, :path => VAGRANT_ROOT + "/provisioning/shell/ubuntu_install_jvm.sh"
end