# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_ROOT = "../../../vagrant"

Vagrant.configure("2") do |config|
  config.vm.box = "Ubuntu32-12.04LTS"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.hostname = "apm"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :private_network, ip: "192.168.33.10", auto_correct: true
  # config.vm.network :public_network
  # config.ssh.forward_agent = false
  config.vm.synced_folder VAGRANT_ROOT, "/vagrant"

  # config.vm.provider :virtualbox do |vb|
  #   vb.gui = false
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  #   vb.customize ["modifyvm", :id, "--cpus", "4"]
  #   vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  # end
  
  config.vm.provision :shell, :path => VAGRANT_ROOT + "/provisioning/shell/ubuntu_install_apm.sh"

  # config.vm.provision :chef_solo do |chef|
  #   chef.cookbooks_path = VAGRANT_ROOT + "/provisioning/chef/cookbooks"
  #   chef.add_recipe "mysql::server"
  #   chef.add_recipe "apache2"
  #   chef.add_recipe "php"
  #   chef.json = {
  #     :mysql => {
  #       :server_root_password => "vagrant",
  #       :server_repl_password => "vagrant",
  #       :server_debian_password => "vagrant"
  #     }
  #   }
  # end
end
